"""Aggregation of per-run results: summary tables (mean +/- std), paired
backbone comparisons and figures."""
from pathlib import Path
from typing import List, Sequence

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon

from .metrics import METRICS

GROUP_COLS = ["experiment", "dataset", "backbone", "method", "label_frac"]
PAIR_COLS = ["dataset", "method", "split", "seed", "label_frac"]


def summarize(raw: pd.DataFrame, metrics: Sequence[str] = METRICS) -> pd.DataFrame:
    """Mean, sample std (ddof=1, as pandas used in the conference tables) and n per setting."""
    g = raw.groupby(GROUP_COLS, dropna=False)
    out = g[list(metrics)].agg(["mean", "std", "count"])
    out.columns = [f"{m}_{s if s != 'count' else 'n'}" for m, s in out.columns]
    out = out.reset_index()
    out["n_runs"] = g.size().values
    return out


def paired_comparison(raw: pd.DataFrame, reference: str, metrics: Sequence[str] = METRICS) -> pd.DataFrame:
    """For every backbone != ``reference``: mean/std of (backbone - reference) over runs
    matched on dataset, method, split, seed and label fraction, with a two-sided
    Wilcoxon signed-rank p-value. With n=9 pairs the smallest possible p is 2/512."""
    ref = raw[raw.backbone == reference].set_index(PAIR_COLS)
    rows = []
    for b in sorted(set(raw.backbone) - {reference}):
        other = raw[raw.backbone == b].set_index(PAIR_COLS)
        joined = other[list(metrics)].join(ref[list(metrics)], rsuffix="_ref", how="inner")
        for (ds, meth, frac), grp in joined.groupby(level=["dataset", "method", "label_frac"]):
            row = {"dataset": ds, "method": meth, "label_frac": frac, "backbone": b,
                   "reference": reference, "n_pairs": len(grp)}
            for m in metrics:
                d = (grp[m] - grp[f"{m}_ref"]).to_numpy()
                row[f"{m}_diff_mean"] = float(np.mean(d))
                row[f"{m}_diff_std"] = float(np.std(d, ddof=1)) if len(d) > 1 else float("nan")
                try:
                    row[f"{m}_wilcoxon_p"] = float(wilcoxon(d).pvalue) if np.any(d != 0) else 1.0
                except ValueError:
                    row[f"{m}_wilcoxon_p"] = float("nan")
            rows.append(row)
    return pd.DataFrame(rows)


def _fmt(mean: float, std: float, digits: int = 3) -> str:
    if pd.isna(mean):
        return "--"
    return f"{mean:.{digits}f} $\\pm$ {std:.{digits}f}" if not pd.isna(std) else f"{mean:.{digits}f}"


def to_latex(summary: pd.DataFrame, path: Path, metrics: Sequence[str] = METRICS, caption: str = "") -> None:
    """Booktabs table, one row per setting, cells as mean $\\pm$ std."""
    from .plotting import BACKBONE_LABELS, DATASET_LABELS, METHOD_STYLES, METRIC_LABELS
    cols = "lllr" + "c" * len(metrics)
    lines = [
        "% Generated by scripts/aggregate.py -- do not edit by hand",
        "\\begin{table}", "\\centering", f"\\caption{{{caption}}}" if caption else "",
        f"\\begin{{tabular}}{{{cols}}}", "\\toprule",
        "Dataset & Backbone & Method & Labels & " + " & ".join(METRIC_LABELS.get(m, m) for m in metrics) + " \\\\",
        "\\midrule",
    ]
    prev_ds = None
    for _, r in summary.iterrows():
        if prev_ds is not None and r.dataset != prev_ds:
            lines.append("\\midrule")
        prev_ds = r.dataset
        cells = [DATASET_LABELS.get(r.dataset, r.dataset), BACKBONE_LABELS.get(r.backbone, r.backbone),
                 METHOD_STYLES.get(r.method, {}).get("label", r.method), f"{r.label_frac * 100:g}\\%"]
        cells += [_fmt(r[f"{m}_mean"], r[f"{m}_std"]) for m in metrics]
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    path.write_text("\n".join(line for line in lines if line != ""))


def check_completeness(summary: pd.DataFrame, expected: int) -> List[str]:
    bad = summary[summary["n_runs"] != expected]
    return [f"{r.experiment}/{r.dataset}/{r.backbone}/{r.method}/{r.label_frac:g}: n={r.n_runs} (expected {expected})"
            for r in bad.itertuples()]
